version: '3.8'

services:
  app:
    container_name: hacktoberfest_projects_prod
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
      target: prod
    restart: on-failure
    ports:
      - 3000:3000
