version: '3.8'

services:
  app:
    container_name: hacktoberfest_projects_dev
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
      target: dev
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ../:/app
      - /app/node_modules
      - /app/.next
